name: TownConnect
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    majorVersion: 2.0.0
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    INFOPLIST_FILE: TownConnect/Resources/Info.plist
targets:
  TownConnect:
    type: application
    platform: iOS
    sources:
      - path: TownConnect
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.townconnect
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - TownConnectTests
    dependencies:
      - package: Supabase
        product: Supabase

  TownConnectTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TownConnectTests
    dependencies:
      - target: TownConnect
